"""Database creation

Revision ID: 531b18ff937b
Revises: 
Create Date: 2024-01-21 15:41:11.953833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '531b18ff937b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('menu_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('menu_uuid')
    )
    op.create_table('submenu',
    sa.Column('submenu_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('menu_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['menu_uuid'], ['menu.menu_uuid'], ),
    sa.PrimaryKeyConstraint('submenu_uuid')
    )
    op.create_table('dish',
    sa.Column('dish_uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('submenu_uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['submenu_uuid'], ['submenu.submenu_uuid'], ),
    sa.PrimaryKeyConstraint('dish_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish')
    op.drop_table('submenu')
    op.drop_table('menu')
    # ### end Alembic commands ###
